DELETE FROM KINDRED.FRIEND_STATUS s WHERE s.STATUS in ('PENDING', 'ACCEPTED','REJECTED','BLOCKED');
INSERT INTO KINDRED.FRIEND_STATUS s (s.status) VALUES ('PENDING');
INSERT INTO KINDRED.FRIEND_STATUS s (s.status) VALUES ('ACCEPTED');
INSERT INTO KINDRED.FRIEND_STATUS s (s.status) VALUES ('REJECTED');
INSERT INTO KINDRED.FRIEND_STATUS s (s.status) VALUES ('BLOCKED');