DELETE FROM KINDRED.REACTION r WHERE r.REACTION_TYPE in ('LIKE', 'LOVE','HAHA','SAD','ANGRY');
INSERT INTO KINDRED.REACTION r (r.REACTION_TYPE) VALUES ('LIKE');
INSERT INTO KINDRED.REACTION r (r.REACTION_TYPE) VALUES ('LOVE');
INSERT INTO KINDRED.REACTION r (r.REACTION_TYPE) VALUES ('HAHA');
INSERT INTO KINDRED.REACTION r (r.REACTION_TYPE) VALUES ('SAD');
INSERT INTO KINDRED.REACTION r (r.REACTION_TYPE) VALUES ('ANGRY');